/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora_de_numeros_complejos;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JPanel;

/**
 *
 * @author dorad
 */
public class Vista extends javax.swing.JFrame {
        
    float real1;
    float imaginario1;
    float real2;
    float imaginario2;

    char operacion;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form vista
     */
    public Vista() {
        setTitle("Vista");
        setSize(400,400);
        setLocationRelativeTo(null);
        initComponents();
        setFocusable(true);
    requestFocusInWindow();

    addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent e) {

            char tecla = e.getKeyChar();

if (tecla == '.') {

    String texto = jTextField1.getText();

    int ultimoOperador = Math.max(
        Math.max(texto.lastIndexOf("+"), texto.lastIndexOf("-")),
        Math.max(texto.lastIndexOf("*"), texto.lastIndexOf("/"))
    );

    String numeroActual = texto.substring(ultimoOperador + 1);

    if (!numeroActual.contains(".")) {
        jTextField1.setText(texto + ".");
    }

} else if ((tecla >= '0' && tecla <= '9') ||
           tecla == '+' ||
           tecla == '-' ||
           tecla == '*' ||
           tecla == '/' ||
           tecla == '(' ||
           tecla == ')' ||
           tecla == 'i') {

    jTextField1.setText(jTextField1.getText() + tecla);
}

            if (tecla == '=') {
                RESULTActionPerformed(null);
            }
        }
    
    public void keyPressed(java.awt.event.KeyEvent e) {

        // Tecla Backspace
        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE) {

            String texto = jTextField1.getText();

            if (texto.length() > 0) {
                jTextField1.setText(
                    texto.substring(0, texto.length() - 1)
                );
            }
        }

        // Tecla Escape = C
        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            CActionPerformed(null);
        }
    }
    });
}
        
    /**
     *        conectarBotones(getContentPane()); 
 This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DOS = new javax.swing.JButton();
        TRES = new javax.swing.JButton();
        SUMA = new javax.swing.JButton();
        UNO = new javax.swing.JButton();
        CUATRO = new javax.swing.JButton();
        CINCO = new javax.swing.JButton();
        SEIS = new javax.swing.JButton();
        RESTA = new javax.swing.JButton();
        SIETE = new javax.swing.JButton();
        OCHO = new javax.swing.JButton();
        NUEVE = new javax.swing.JButton();
        MULTI = new javax.swing.JButton();
        CERO = new javax.swing.JButton();
        POINT = new javax.swing.JButton();
        NEGPOS = new javax.swing.JButton();
        DIVIDIR = new javax.swing.JButton();
        PARENTIZQ = new javax.swing.JButton();
        PARENTDER = new javax.swing.JButton();
        i = new javax.swing.JButton();
        C = new javax.swing.JButton();
        RESULT = new javax.swing.JButton();
        DEL = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jButton17.setText("1");
        jButton17.addActionListener(this::jButton17ActionPerformed);

        jButton18.setText("1");
        jButton18.addActionListener(this::jButton18ActionPerformed);

        jButton19.setText("1");
        jButton19.addActionListener(this::jButton19ActionPerformed);

        jButton20.setText("1");
        jButton20.addActionListener(this::jButton20ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        DOS.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        DOS.setText("2");
        DOS.addActionListener(this::DOSActionPerformed);

        TRES.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        TRES.setText("3");
        TRES.addActionListener(this::TRESActionPerformed);

        SUMA.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        SUMA.setText("+");
        SUMA.addActionListener(this::SUMAActionPerformed);

        UNO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        UNO.setText("1");
        UNO.addActionListener(this::UNOActionPerformed);

        CUATRO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        CUATRO.setText("4");
        CUATRO.addActionListener(this::CUATROActionPerformed);

        CINCO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        CINCO.setText("5");
        CINCO.addActionListener(this::CINCOActionPerformed);

        SEIS.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        SEIS.setText("6");
        SEIS.addActionListener(this::SEISActionPerformed);

        RESTA.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RESTA.setText("-");
        RESTA.addActionListener(this::RESTAActionPerformed);

        SIETE.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        SIETE.setText("7");
        SIETE.addActionListener(this::SIETEActionPerformed);

        OCHO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        OCHO.setText("8");
        OCHO.addActionListener(this::OCHOActionPerformed);

        NUEVE.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        NUEVE.setText("9");
        NUEVE.addActionListener(this::NUEVEActionPerformed);

        MULTI.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MULTI.setText("*");
        MULTI.addActionListener(this::MULTIActionPerformed);

        CERO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        CERO.setText("0");
        CERO.addActionListener(this::CEROActionPerformed);

        POINT.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        POINT.setText(".");
        POINT.addActionListener(this::POINTActionPerformed);

        NEGPOS.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        NEGPOS.setText("+/-");
        NEGPOS.addActionListener(this::NEGPOSActionPerformed);

        DIVIDIR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        DIVIDIR.setText("/");
        DIVIDIR.addActionListener(this::DIVIDIRActionPerformed);

        PARENTIZQ.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        PARENTIZQ.setText("(");
        PARENTIZQ.addActionListener(this::PARENTIZQActionPerformed);

        PARENTDER.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        PARENTDER.setText(")");
        PARENTDER.addActionListener(this::PARENTDERActionPerformed);

        i.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        i.setText("i");
        i.addActionListener(this::iActionPerformed);

        C.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        C.setText("C");
        C.addActionListener(this::CActionPerformed);

        RESULT.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RESULT.setText("=");
        RESULT.addActionListener(this::RESULTActionPerformed);

        DEL.setText("⌫");
        DEL.addActionListener(this::DELActionPerformed);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(CERO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(POINT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NEGPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DIVIDIR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(SIETE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(OCHO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUEVE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MULTI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RESTA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(UNO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DOS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TRES, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SUMA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RESULT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PARENTIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PARENTDER, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TRES, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SUMA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UNO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RESTA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OCHO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUEVE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MULTI, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIETE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(POINT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NEGPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DIVIDIR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CERO, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PARENTDER, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PARENTIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RESULT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOSActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_DOSActionPerformed

    private void TRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRESActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_TRESActionPerformed

    private void SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMAActionPerformed
        // TODO add your handling code here:
        operacion = '+';

    jTextField1.setText(jTextField1.getText() + "+");

    }//GEN-LAST:event_SUMAActionPerformed

    private void UNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNOActionPerformed
        // TODO add your handling code here:
        
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_UNOActionPerformed

    private void CUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUATROActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_CUATROActionPerformed

    private void CINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CINCOActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_CINCOActionPerformed

    private void SEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEISActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_SEISActionPerformed

    private void RESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAActionPerformed
        // TODO add your handling code here:
            operacion = '-';

    jTextField1.setText(jTextField1.getText() + "-");

    }//GEN-LAST:event_RESTAActionPerformed

    private void SIETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIETEActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_SIETEActionPerformed

    private void OCHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCHOActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_OCHOActionPerformed

    private void NUEVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVEActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_NUEVEActionPerformed

    private void MULTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIActionPerformed
        // TODO add your handling code here:
        operacion = '*';

    jTextField1.setText(jTextField1.getText() + "*");


    }//GEN-LAST:event_MULTIActionPerformed

    private void CEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEROActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_CEROActionPerformed

    private void POINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POINTActionPerformed
        // TODO add your handling code here:
        String texto = jTextField1.getText();

int ultimoOperador = Math.max(
    Math.max(texto.lastIndexOf("+"), texto.lastIndexOf("-")),
    Math.max(texto.lastIndexOf("*"), texto.lastIndexOf("/"))
);

String numeroActual = texto.substring(ultimoOperador + 1);

if (!numeroActual.contains(".")) {
    jTextField1.setText(texto + ".");
}
    }//GEN-LAST:event_POINTActionPerformed

    private void NEGPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEGPOSActionPerformed
        // TODO add your handling code here:

    String texto = jTextField1.getText();

    if (texto.length() > 0) {

        if (texto.charAt(0) == '-') {
            jTextField1.setText(texto.substring(1));
        } else {
            jTextField1.setText("-" + texto);
        }

    }


    }//GEN-LAST:event_NEGPOSActionPerformed

    private void DIVIDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVIDIRActionPerformed
        // TODO add your handling code here:
        operacion = '/';

    jTextField1.setText(jTextField1.getText() + "/");


    }//GEN-LAST:event_DIVIDIRActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void PARENTIZQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARENTIZQActionPerformed
        // TODO add your handling code here:

    jTextField1.setText(jTextField1.getText() + "(");


    }//GEN-LAST:event_PARENTIZQActionPerformed

    private void PARENTDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARENTDERActionPerformed
        // TODO add your handling code here:
            jTextField1.setText(jTextField1.getText() + ")");

    }//GEN-LAST:event_PARENTDERActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "i");
    }//GEN-LAST:event_iActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:

    jTextField1.setText("");
    jTextField2.setText("");

    real1 = 0;
    imaginario1 = 0;
    real2 = 0;
    imaginario2 = 0;


    }//GEN-LAST:event_CActionPerformed

    private void RESULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTActionPerformed
        // TODO add your handling code here:
         String cadena = jTextField1.getText();

    int i = 0;

    float real1 = 0;
    float imaginario1 = 0;
    float real2 = 0;
    float imaginario2 = 0;

    // Buscar los dos números complejos
    Pattern patron = Pattern.compile(
        "\\(([+-]?\\d+(?:\\.\\d+)?)([+-]\\d+(?:\\.\\d+)?)i\\)"
    );

    Matcher matcher = patron.matcher(cadena);

    while (matcher.find()) {

        float real = Float.parseFloat(matcher.group(1));
        float imaginario = Float.parseFloat(matcher.group(2));

        if (i == 0) {
            real1 = real;
            imaginario1 = imaginario;
        }

        if (i == 1) {
            real2 = real;
            imaginario2 = imaginario;
        }

        i++;
    }

    // Buscar la operación entre los paréntesis
    int primero = cadena.indexOf(")");
    int segundo = cadena.indexOf("(", primero);

    if (primero != -1 && segundo != -1) {

        operacion = cadena.charAt(primero + 1);
    }

    float real = 0;
    float imaginario = 0;

    if (i == 2) {

        if (operacion == '+') {

            real = real1 + real2;
            imaginario = imaginario1 + imaginario2;

        } else if (operacion == '-') {

            real = real1 - real2;
            imaginario = imaginario1 - imaginario2;

        } else if (operacion == '*') {

            real = (real1 * real2) - 
                   (imaginario1 * imaginario2);

            imaginario = (real1 * imaginario2) + 
                         (imaginario1 * real2);

        } else if (operacion == '/') {

            float denominador = 
                    (real2 * real2) + 
                    (imaginario2 * imaginario2);

            if (denominador != 0) {

                real = ((real1 * real2) + 
                        (imaginario1 * imaginario2)) 
                        / denominador;

                imaginario = ((imaginario1 * real2) - 
                              (real1 * imaginario2)) 
                              / denominador;

            } else {

                jTextField2.setText("Error");
                return;
            }
        }

        jTextField2.setText(
            real + " + " + imaginario + "i"
        );

    } else {

        jTextField2.setText("Error");
    }
    }//GEN-LAST:event_RESULTActionPerformed

    private void DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELActionPerformed
        // TODO add your handling code here:

    String texto = jTextField1.getText();

    if (texto.length() > 0) {
        jTextField1.setText(texto.substring(0, texto.length() - 1));
    }


    }//GEN-LAST:event_DELActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JButton CERO;
    private javax.swing.JButton CINCO;
    private javax.swing.JButton CUATRO;
    private javax.swing.JButton DEL;
    private javax.swing.JButton DIVIDIR;
    private javax.swing.JButton DOS;
    private javax.swing.JButton MULTI;
    private javax.swing.JButton NEGPOS;
    private javax.swing.JButton NUEVE;
    private javax.swing.JButton OCHO;
    private javax.swing.JButton PARENTDER;
    private javax.swing.JButton PARENTIZQ;
    private javax.swing.JButton POINT;
    private javax.swing.JButton RESTA;
    private javax.swing.JButton RESULT;
    private javax.swing.JButton SEIS;
    private javax.swing.JButton SIETE;
    private javax.swing.JButton SUMA;
    private javax.swing.JButton TRES;
    private javax.swing.JButton UNO;
    private javax.swing.JButton i;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    
}
